config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # create the root for the index
  root "flats#index"

  get "flats/:id", to: "flats#show", as: :flat
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require "open-uri"

class FlatsController < ApplicationController
  URL = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
  before_action :set_flats

  def index
  end

  def show
    # get the flat according to the params[:id]
    @flat = @flats.find { |flat| flat["id"] == params[:id].to_i }
  end

  private

  def set_flats
    @flats = JSON.parse(URI.open(URL).read)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container my-4">
  <h1>Flats</h1>

  <ul>
    <% @flats.each do |flat| %>
      <li>
        <%= link_to flat_path(flat["id"])  do %>
        <h2>
          <%= flat["name"] %>
        </h2>
        <p><%= flat["price"] %> <%= flat["priceCurrency"] %></p>
        <% end %>

      </li>
    <% end %>
  </ul>

</div>

app/views/flats/show.html.erb
<h1><%= @flat["name"] %></h1>
<h2><%= @flat["price"] %> <%= @flat["priceCurrency"] %></h2>
<%# For Rails, use image_tag %>

<%= image_tag @flat["imageUrl"], alt: @flat["name"], width: 500 %>

<%= link_to "Go Back", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbStatic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>